[workspace]
members = ["aggregator", "api", "db", "types", "indexer"]
exclude = ["dependencies", "sdk"]

[workspace.dependencies]
bigdecimal = "^0.3.0"
chrono = "^0.4.24"
dotenvy = "^0.15.6"
envy = "^0.4.2"
futures-util = "^0.3.26"
serde = { version = "^1.0.149", features = ["derive"] }
serde_json = "^1.0.93"
sqlx = { version = "^0.6.2", features = ["runtime-tokio-rustls"] }
thiserror = "^1.0.38"
tokio = "^1.25.0"
