version: "3.9"

include:
  - compose.dss-core.yaml

services:
    processsor:
      depends_on:
        diesel:
          condition: service_completed_successfully
      environment:
        - HEALTHCHECK_BEFORE_START=false
      extends:
        file: compose.processor-template.yaml
        service: processor-template
