[package]
name = "api"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.18", features = ["query", "ws"] }
bigdecimal = { workspace = true }
chrono = { workspace = true }
db = { path = "../db", features = ["sqlx"] }
dotenvy = { workspace = true }
envy = { workspace = true }
futures-util = { workspace = true }
once_cell = "1.17.1"
redis = { version = "0.23.0", features = [
    "tokio-comp",
    "tokio-native-tls-comp",
    "r2d2",
] }
regex = "1.8.1"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
sqlx = { workspace = true, features = [
    "bigdecimal",
    "chrono",
    "macros",
    "offline",
    "postgres",
    "runtime-tokio-rustls",
    "time",
] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = "0.4.13"
tower-http = { version = "0.4.0", features = [
    "compression-br",
    "cors",
    "trace",
] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
types = { path = "../types", features = ["serde"] }

[dev-dependencies]
hyper = "0.14.26"
rand = { version = "0.8.5", features = ["std_rng"] }
tokio-tungstenite = "0.18.0"
url = "2.3.1"
