[package]
name = 'Econia'
version = '4.0.0' # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia = '0xc0deb00c9154b6b64db01eeb77d08255300315e1fa35b687d384a703f6034fbd'
# Mock addresses for testing.
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
integrator = '0x4567'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'bdb970012daeb3617f8c441b7658605d9f6cdb8b'