[package]
name = 'Econia'
version = '4.0.0' # Per SemVer.
upgrade_policy = 'compatible'

[addresses]
econia = '0x2e51979739db25dc987bd24e1a968e45cca0e0daea7cae9121f68af93e8884c9'
# Mock addresses for testing.
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
integrator = '0x4567'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
subdir = 'aptos-move/framework/aptos-framework'
rev = 'mainnet'