[package]
name = "Econia"
version = "4.1.0"                                     # Per SemVer.
upgrade_policy = "compatible"
authors = ["Econia Labs (developers@econialabs.com)"]

[addresses]
econia = "_"
# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"
integrator = "0x4567"

[dependencies.EconiaTestnetCompetitionThrottler]
local = "../testnet-competition-throttler"