[package]
name = "Econia"
version = "4.0.1"             # Per SemVer.
upgrade_policy = "compatible"

[addresses]
econia = "0x40b119411c6a975fca28f1ba5800a8a418bba1e16a3f13b1de92f731e023d135"
# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"
integrator = "0x4567"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
