[package]
name = 'Econia'
version = '3.0.0' # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia = '0xc0deb00c9154b6b64db01eeb77d08255300315e1fa35b687d384a703f6034fbd'
# Mock users for unit tests
user = '0x1234'
user_0 = '0x2345'
user_1 = '0x3456'
user_2 = '0x4567'
user_3 = '0x5678'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = '83c126f7e176f21074f520f7f65ed4cbab3476b0'
