[package]
name = "Econia"
version = "4.1.0"                                     # Per SemVer.
upgrade_policy = "compatible"
authors = ["Econia Labs (developers@econialabs.com)"]

[addresses]
econia = "_"
# Mock addresses for testing.
user = "0x1234"
user_0 = "0x2345"
user_1 = "0x3456"
user_2 = "0x2222"
user_3 = "0x3333"
user_4 = "0x4444"
integrator = "0x4567"

[dev-addresses]
econia = "0xdeaddead"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
# You may need to change this to `main` to run event unit tests, since
# event unit tests for this package were added before Aptos' event unit
# testing framework was incorporated into the `mainnet` branch.
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
