[package]
name = "EconiaFaucet"
version = '1.0.0'             # Per SemVer
upgrade_policy = 'compatible'

[addresses]
econia_faucet = "_"

[dependencies.EconiaTestnetCompetitionThrottler]
local = "../testnet-competition-throttler"
